version: '3.8'
services:
  db:
    image: postgres
    container_name: dafiti_db
    environment:
      - POSTGRES_DB=dafiti
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
  dafiti:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    container_name: dafiti_container
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db